/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables.records;


import edu.java.domain.jooq.tables.GithubLinkInfo;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.impl.TableRecordImpl;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GithubLinkInfoRecord extends TableRecordImpl<GithubLinkInfoRecord> {

    private static final long serialVersionUID = 1L;

    public void setId(@Nullable Long value) {
        set(0, value);
    }

    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    public void setLinkId(@NotNull Long value) {
        set(1, value);
    }

    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return (Long) get(1);
    }

    public void setLastEventId(@NotNull Long value) {
        set(2, value);
    }

    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLastEventId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public GithubLinkInfoRecord() {
        super(GithubLinkInfo.GITHUB_LINK_INFO);
    }

    @ConstructorProperties({ "id", "linkId", "lastEventId" })
    public GithubLinkInfoRecord(@Nullable Long id, @NotNull Long linkId, @NotNull Long lastEventId) {
        super(GithubLinkInfo.GITHUB_LINK_INFO);

        setId(id);
        setLinkId(linkId);
        setLastEventId(lastEventId);
        resetChangedOnNotNull();
    }

    public GithubLinkInfoRecord(edu.java.domain.jooq.tables.pojos.GithubLinkInfo value) {
        super(GithubLinkInfo.GITHUB_LINK_INFO);

        if (value != null) {
            setId(value.getId());
            setLinkId(value.getLinkId());
            setLastEventId(value.getLastEventId());
            resetChangedOnNotNull();
        }
    }
}
