/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables.records;

import edu.java.domain.jooq.tables.Link;
import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.impl.TableRecordImpl;

@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class LinkRecord extends TableRecordImpl<LinkRecord> {

    private static final long serialVersionUID = 1L;

    public LinkRecord() {
        super(Link.LINK);
    }

    @ConstructorProperties({"id", "url", "name", "createdAt", "lastUpdateTime", "lastCheckTime"})
    public LinkRecord(
        @Nullable Long id,
        @NotNull String url,
        @Nullable String name,
        @NotNull OffsetDateTime createdAt,
        @NotNull OffsetDateTime lastUpdateTime,
        @NotNull OffsetDateTime lastCheckTime
    ) {
        super(Link.LINK);

        setId(id);
        setUrl(url);
        setName(name);
        setCreatedAt(createdAt);
        setLastUpdateTime(lastUpdateTime);
        setLastCheckTime(lastCheckTime);
        resetChangedOnNotNull();
    }

    public LinkRecord(edu.java.domain.jooq.tables.pojos.Link value) {
        super(Link.LINK);

        if (value != null) {
            setId(value.getId());
            setUrl(value.getUrl());
            setName(value.getName());
            setCreatedAt(value.getCreatedAt());
            setLastUpdateTime(value.getLastUpdateTime());
            setLastCheckTime(value.getLastCheckTime());
            resetChangedOnNotNull();
        }
    }

    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    public void setId(@Nullable Long value) {
        set(0, value);
    }

    @jakarta.validation.constraints.NotNull
    @Size(max = 1000000000)
    @NotNull
    public String getUrl() {
        return (String) get(1);
    }

    public void setUrl(@NotNull String value) {
        set(1, value);
    }

    @Size(max = 1000000000)
    @Nullable
    public String getName() {
        return (String) get(2);
    }

    public void setName(@Nullable String value) {
        set(2, value);
    }

    @jakarta.validation.constraints.NotNull
    @NotNull
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    public void setCreatedAt(@NotNull OffsetDateTime value) {
        set(3, value);
    }

    @jakarta.validation.constraints.NotNull
    @NotNull
    public OffsetDateTime getLastUpdateTime() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public void setLastUpdateTime(@NotNull OffsetDateTime value) {
        set(4, value);
    }

    @jakarta.validation.constraints.NotNull
    @NotNull
    public OffsetDateTime getLastCheckTime() {
        return (OffsetDateTime) get(5);
    }

    public void setLastCheckTime(@NotNull OffsetDateTime value) {
        set(5, value);
    }
}
