/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables.records;

import edu.java.domain.jooq.tables.LinkTgChat;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.Nullable;
import org.jooq.impl.TableRecordImpl;

@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class LinkTgChatRecord extends TableRecordImpl<LinkTgChatRecord> {

    private static final long serialVersionUID = 1L;

    public LinkTgChatRecord() {
        super(LinkTgChat.LINK_TG_CHAT);
    }

    @ConstructorProperties({"tgChatId", "linkId"})
    public LinkTgChatRecord(@Nullable Long tgChatId, @Nullable Long linkId) {
        super(LinkTgChat.LINK_TG_CHAT);

        setTgChatId(tgChatId);
        setLinkId(linkId);
        resetChangedOnNotNull();
    }

    public LinkTgChatRecord(edu.java.domain.jooq.tables.pojos.LinkTgChat value) {
        super(LinkTgChat.LINK_TG_CHAT);

        if (value != null) {
            setTgChatId(value.getTgChatId());
            setLinkId(value.getLinkId());
            resetChangedOnNotNull();
        }
    }

    @Nullable
    public Long getTgChatId() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public void setTgChatId(@Nullable Long value) {
        set(0, value);
    }

    @Nullable
    public Long getLinkId() {
        return (Long) get(1);
    }

    public void setLinkId(@Nullable Long value) {
        set(1, value);
    }
}
