/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables.records;

import edu.java.domain.jooq.tables.TgChat;
import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.impl.TableRecordImpl;

@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TgChatRecord extends TableRecordImpl<TgChatRecord> {

    private static final long serialVersionUID = 1L;

    public TgChatRecord() {
        super(TgChat.TG_CHAT);
    }

    @ConstructorProperties({"id", "chatId", "name"})
    public TgChatRecord(@Nullable Long id, @NotNull Long chatId, @NotNull String name) {
        super(TgChat.TG_CHAT);

        setId(id);
        setChatId(chatId);
        setName(name);
        resetChangedOnNotNull();
    }

    public TgChatRecord(edu.java.domain.jooq.tables.pojos.TgChat value) {
        super(TgChat.TG_CHAT);

        if (value != null) {
            setId(value.getId());
            setChatId(value.getChatId());
            setName(value.getName());
            resetChangedOnNotNull();
        }
    }

    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    public void setId(@Nullable Long value) {
        set(0, value);
    }

    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public void setChatId(@NotNull Long value) {
        set(1, value);
    }

    @jakarta.validation.constraints.NotNull
    @Size(max = 1000000000)
    @NotNull
    public String getName() {
        return (String) get(2);
    }

    public void setName(@NotNull String value) {
        set(2, value);
    }
}
