app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

api:
  github:
    connection-timeout: 10s
    url: https://api.github.com
  stackoverflow:
    connection-timeout: 10s
    url: https://api.stackexchange.com
    uri-parameters:
      site: stackoverflow

tgbot:
  url: http://localhost:8090
  connection-timeout: 10s

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
