app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  linkChecker:
    checkInterval: 7s

api:
  github:
    connection-timeout: 10s
    url: https://api.github.com
  stackoverflow:
    connection-timeout: 10s
    url: https://api.stackexchange.com
    uri-parameters:
      site: stackoverflow

tgbot:
  url: http://localhost:8090
  connection-timeout: 10s

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
