app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  linkChecker:
    checkInterval: 15s
  database-access-type: jpa

api:
  github:
    connection-timeout: 10s
    url: https://api.github.com
    retry:
      max-attempts: 3
      strategy: linear
      interval: 3s
      codes:
        - 500
  stackoverflow:
    connection-timeout: 10s
    url: https://api.stackexchange.com
    uri-parameters:
      site: stackoverflow
    retry:
      max-attempts: 3
      strategy: linear
      interval: 3s
      codes:
        - 500

tgbot:
  url: http://localhost:8090
  connection-timeout: 10s
  retry:
    max-attempts: 3
    strategy: linear
    interval: 3s
    codes:
      - 500

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
