app:
  telegram-token: ${TG_TOKEN}
  useQueue: true
  kafka-updates-topic:
    name: updatesTopic
    partitions: 10
    replicas: 1

scrapper:
  url: http://localhost:8080
  connection-timeout: 10s

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  kafka:
    consumer:
      group-id: link-updates
      value-deserializer: edu.java.bot.configuration.kafka.LinkUpdateRequestDeserializer


server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
