app:
  telegram-token: ${TG_TOKEN}

scrapper:
  url: http://localhost:8080
  connection-timeout: 10s

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
