app:
  telegram-token: unset

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  profiles:
    active:
      dev

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
