/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables;


import edu.java.domain.jooq.DefaultSchema;
import edu.java.domain.jooq.tables.records.LinkTgChatRecord;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LinkTgChat extends TableImpl<LinkTgChatRecord> {

    private static final long serialVersionUID = 1L;

    public static final LinkTgChat LINK_TG_CHAT = new LinkTgChat();

    @Override
    @NotNull
    public Class<LinkTgChatRecord> getRecordType() {
        return LinkTgChatRecord.class;
    }

    public final TableField<LinkTgChatRecord, Long> TG_CHAT_ID = createField(DSL.name("TG_CHAT_ID"), SQLDataType.BIGINT, this, "");

    public final TableField<LinkTgChatRecord, Long> LINK_ID = createField(DSL.name("LINK_ID"), SQLDataType.BIGINT, this, "");

    private LinkTgChat(Name alias, Table<LinkTgChatRecord> aliased) {
        this(alias, aliased, null);
    }

    private LinkTgChat(Name alias, Table<LinkTgChatRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public LinkTgChat(String alias) {
        this(DSL.name(alias), LINK_TG_CHAT);
    }

    public LinkTgChat(Name alias) {
        this(alias, LINK_TG_CHAT);
    }

    public LinkTgChat() {
        this(DSL.name("LINK_TG_CHAT"), null);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public LinkTgChat as(String alias) {
        return new LinkTgChat(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public LinkTgChat as(Name alias) {
        return new LinkTgChat(alias, this);
    }

    @Override
    @NotNull
    public LinkTgChat as(Table<?> alias) {
        return new LinkTgChat(alias.getQualifiedName(), this);
    }

    @Override
    @NotNull
    public LinkTgChat rename(String name) {
        return new LinkTgChat(DSL.name(name), null);
    }

    @Override
    @NotNull
    public LinkTgChat rename(Name name) {
        return new LinkTgChat(name, null);
    }

    @Override
    @NotNull
    public LinkTgChat rename(Table<?> name) {
        return new LinkTgChat(name.getQualifiedName(), null);
    }
}
