/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables;

import edu.java.domain.jooq.DefaultSchema;
import edu.java.domain.jooq.tables.records.LinkRecord;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Link extends TableImpl<LinkRecord> {

    public static final Link LINK = new Link();
    private static final long serialVersionUID = 1L;
    public final TableField<LinkRecord, Long> ID =
        createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");
    public final TableField<LinkRecord, String> URL =
        createField(DSL.name("URL"), SQLDataType.VARCHAR(1000000000).nullable(false), this, "");
    public final TableField<LinkRecord, String> NAME =
        createField(DSL.name("NAME"), SQLDataType.VARCHAR(1000000000), this, "");
    public final TableField<LinkRecord, OffsetDateTime> CREATED_AT =
        createField(DSL.name("CREATED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");
    public final TableField<LinkRecord, OffsetDateTime> LAST_UPDATE_TIME =
        createField(DSL.name("LAST_UPDATE_TIME"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");
    public final TableField<LinkRecord, OffsetDateTime> LAST_CHECK_TIME =
        createField(DSL.name("LAST_CHECK_TIME"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private Link(Name alias, Table<LinkRecord> aliased) {
        this(alias, aliased, null);
    }

    private Link(Name alias, Table<LinkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public Link(String alias) {
        this(DSL.name(alias), LINK);
    }

    public Link(Name alias) {
        this(alias, LINK);
    }

    public Link() {
        this(DSL.name("LINK"), null);
    }

    @Override
    @NotNull
    public Class<LinkRecord> getRecordType() {
        return LinkRecord.class;
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Link as(String alias) {
        return new Link(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public Link as(Name alias) {
        return new Link(alias, this);
    }

    @Override
    @NotNull
    public Link as(Table<?> alias) {
        return new Link(alias.getQualifiedName(), this);
    }

    @Override
    @NotNull
    public Link rename(String name) {
        return new Link(DSL.name(name), null);
    }

    @Override
    @NotNull
    public Link rename(Name name) {
        return new Link(name, null);
    }

    @Override
    @NotNull
    public Link rename(Table<?> name) {
        return new Link(name.getQualifiedName(), null);
    }
}
