/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.Nullable;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LinkTgChat implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long tgChatId;
    private Long linkId;

    public LinkTgChat() {}

    public LinkTgChat(LinkTgChat value) {
        this.tgChatId = value.tgChatId;
        this.linkId = value.linkId;
    }

    @ConstructorProperties({ "tgChatId", "linkId" })
    public LinkTgChat(
        @Nullable Long tgChatId,
        @Nullable Long linkId
    ) {
        this.tgChatId = tgChatId;
        this.linkId = linkId;
    }

    @Nullable
    public Long getTgChatId() {
        return this.tgChatId;
    }

    public void setTgChatId(@Nullable Long tgChatId) {
        this.tgChatId = tgChatId;
    }

    @Nullable
    public Long getLinkId() {
        return this.linkId;
    }

    public void setLinkId(@Nullable Long linkId) {
        this.linkId = linkId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final LinkTgChat other = (LinkTgChat) obj;
        if (this.tgChatId == null) {
            if (other.tgChatId != null)
                return false;
        }
        else if (!this.tgChatId.equals(other.tgChatId))
            return false;
        if (this.linkId == null) {
            if (other.linkId != null)
                return false;
        }
        else if (!this.linkId.equals(other.linkId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.tgChatId == null) ? 0 : this.tgChatId.hashCode());
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LinkTgChat (");

        sb.append(tgChatId);
        sb.append(", ").append(linkId);

        sb.append(")");
        return sb.toString();
    }
}
