/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq;


import edu.java.domain.jooq.tables.GithubLinkInfo;
import edu.java.domain.jooq.tables.Link;
import edu.java.domain.jooq.tables.LinkTgChat;
import edu.java.domain.jooq.tables.StackoverflowLinkInfo;
import edu.java.domain.jooq.tables.TgChat;

import javax.annotation.processing.Generated;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    public static final GithubLinkInfo GITHUB_LINK_INFO = GithubLinkInfo.GITHUB_LINK_INFO;

    public static final Link LINK = Link.LINK;

    public static final LinkTgChat LINK_TG_CHAT = LinkTgChat.LINK_TG_CHAT;

    public static final StackoverflowLinkInfo STACKOVERFLOW_LINK_INFO = StackoverflowLinkInfo.STACKOVERFLOW_LINK_INFO;

    public static final TgChat TG_CHAT = TgChat.TG_CHAT;
}
